name: Self Test

on:
  schedule:
    - cron: "14 3 * * 5" # every friday at 03:14
  workflow_dispatch:

jobs:
  self-test:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - uses: ./
